name: CI

on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["*"]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          args: --timeout=3m

  test:
    name: Build, Test
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        options: >-
          --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=5
        ports:
          - 6379:6379

      mysql:
        image: mysql:5.7
        options: >-
          --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        env:
          MYSQL_DATABASE: subscan_test
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: make build

      - name: Test
        if: "!contains(steps.check-base.outputs.COMMIT_MESSAGE, '[skip test]')"
        run: |
          go test -v ./...
